# vim ft=yaml
# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

dist: xenial  # Ubuntu 16.04

install:
  - sudo apt-get install libboost-all-dev libtbb-dev

script:
  - ./build.sh
  - ./build/drop/apps/dropreg/dropreg --help

#after_success:
#  - ./build/drop/apps/dropreg/dropreg --help

notifications:
  email: false
